### ISSUE TITLE
How to add configuration options to codehike in Docusaurus?

### ISSUE THREAD

**Issue by C-Loftus** [code-hike/examples#11]
Hello, I have code-hike set up with Docusaurus. It renders the code blocks but doesn't do anything with the code-hike comments. I am unclear on how to add different functionality. I can't seem to find where I would put the remark codehike options like it mentions here https://codehike.org/docs/configuration

For context, I mainly just want to be able to use tooltips, copying text, and maybe highlighting, collapsing. Could you direct me to where I need to add these options? I see https://v1.codehike.org/docs/code/tooltip lists the source for some components, but I am not finding the inline comment // !tooltip[/lorem/] description works for me

![image](https://github.com/user-attachments/assets/de1ebd12-2348-4602-96b1-2fdbc7dc25f0)

Thank you

**Comment by pomber** [comment]
See https://github.com/code-hike/examples/blob/with-docusaurus/with-docusaurus/docusaurus.config.ts#L44

Also docs here https://v1.codehike.org/docs

**Comment by C-Loftus** [comment]
Thanks for your response. I do have the same config and I am applying `beforeDefaultRemarkPlugins: [[remarkCodeHike, chConfig]],`. Is that supposed to allow for tooltips to be applied? 

I tried out the example and it also seems that the comments don't seem to work beyond the callout component which is included. Do you have to create the annotations yourself?

![image](https://github.com/user-attachments/assets/12d4d10e-8ca3-442b-a159-5236c2c22398)

For what it is worth I have read all the v1 docs

**Comment by pomber** [comment]
Yes, you need to add the `AnnotationHandler` for each type of annotation, there are no built-in annotations.
